USERNAME = 'user'
PASSWORD = 'password'
allowed_ips = ['localhost', '127.0.0.1','172.31.45.41', '61.238.232.74','60.181.13.229','122.248.207.203','60.181.9.41']
FILE_SERVER_ENDPOINT = "13.114.67.59:8000/"
OUTPUT_DIR = r"G:/Nexrender_Video_Server/Output_Videos/"
#DOWNLOAD_INITIATOR_ENDPOINT = 'https://122.248.207.203/wcxwebservice/ConfirmVideoGenerate'
DOWNLOAD_INITIATOR_ENDPOINT = 'https://cms.wealthcx.com/wcxwebservice/ConfirmVideoGenerate'
NEXRENDER_CLI_PATH= "G:/Nexrender_Video_Server/nexrender-cli-win64.exe"
TEMP_JSON_PATH = "G:/Desktop/Nexrender/Template-{}/temporary.json"
TEMP_CSV_PATH = "G:/Desktop/Nexrender/Template-{}/(Footage)/03_Data/data.csv"
PRIVATE_KEY_PATH = "G:/Nexrender_Video_Server/wealthcx_sftp.pem"
SFTP_DEST = '/server/wcx_storage/public/video/RFT{}/'     
SFTP_HOST = "122.248.207.203"              
SFTP_USERNAME = "wealthcx"
CONFIRM_API_CERT_PATH = 'G:/Nexrender_Video_Server/confirm_API_cert.crt'
CONFIRM_API_USERNAME = 'nifi'
CONFIRM_API_PASSWORD = 'nifi123'
ERROR_LOGS_PATH = 'G:/Nexrender_Video_Server/error_log/'
NEXRENDER_WORKING_FOLDER = r"C:/temp/nexrender"